import Head from "next/head";
import Header from "@/components/Header/Header";

const links = [
  {
    link: "/shop",
    label: "Shop",
  },
  {
    link: "/about",
    label: "About",
  },
  {
    link: "/contact",
    label: "Contact Us",
  },
  {
    link: "/login",
    label: "Login",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header links={links} />
      </main>
    </>
  );
}
